n=as.integer(readline("enter the number of students"))
usn<-vector(mode = "character",length = n)
name<-vector(mode = "character",length = n)
marks<-vector(mode = "numeric",length = n)
print("enter the students usn")
for (i in 1:n)
  usn[i]<-as.character(readline())
print("enter the name of student")
for(i in 1:n)
  name[i]<-as.character(readline())
print("enter the marks")
for(i in 1:n)
  marks[i]<-as.integer(readline())
student<-data.frame(usn,name,marks)
print("student details")
print(student)
print("enter the age of students")
age<-vector(mode = "numeric",length = n)
for(i in 1:n)
  age[i]<-as.integer(readline())
student<-cbind(student,age)
print(student)
for(i in 1:n)
	if ( student[i,][3] > 25 )
		if (student[i,][4] > 20)
			print(student[i,])


