n=as.integer(readline("enter the no of employees "))
empid<-vector(mode="numeric",length = n)
empname<-vector(mode = "character",length = n)
doj<-vector(mode = "numeric",length = n)
#dmpcode,dept,desig
print("enter the emp id")
for(i in 1:n)
  empid[i]<-as.integer(readline())
print("enter employee name")
for(i in 1:n)
  empname<-as.character(readline())
print("enter date of joining")
for(i in 1:n)
  doj<-as.integer(readline())
employee<-data.frame(empid,empname,doj)
print(employee)
write.csv(employee,"p22.csv")
read.csv("p22.csv")
x=data.frame(123,"hari",2022)
write.table(x,"p22.csv",append = TRUE,quote = FALSE,sep = ",",row.names = TRUE,col.names = FALSE)
read.csv("p22.csv")
